name: CI

on:
    pull_request:
    push:
        branches: [ master ]

jobs:
    run:
        runs-on: ubuntu-18.04
        strategy:
            fail-fast: false
            matrix:
                node-version: ['12', '14', '16']
                coverage: [ 'none' ]
                include:
                    - description: 'Log code coverage'
                      node-version: '16'
                      coverage: 'jest'

        name: Node ${{ matrix.node-version }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install

            - name: Run tests
              run: yarn test
              if: matrix.coverage == 'none'

            - name: Run tests with coverage
              run: yarn coverage
              if: matrix.coverage == 'jest'

            - name: Run codecov
              uses: codecov/codecov-action@v2
              with:
                  directory: coverage
              if: matrix.coverage == 'jest'
